from flask import Flask, send_file, render_template_string

app = Flask(__name__)

@app.route('/')
def index():
    return "Generated by flask" 


@app.route('/greet/<name>')
def greet(name):
    return f"<h1> Greetings {name}</h1> We are so glad to help you today"

@app.route('/download_Vol3')
def download_Vol3():
    file_path = "Ani 03.0 - The Encounter - K. A. Applegate.pdf"
    return send_file(file_path, as_attachment=True)

@app.route('/read_Vol3')
def read_Vol3():
    html_content = """
<h1> Download Animorphs Vol 3</h1>
<p> Click on the link to download the story</p>
<a href="/download_Vol3"> Download Animorphs Vol 3 </a>"""
    return render_template_string(html_content)


if __name__ == "__main__":
    app.run()

